apiVersion: v1
imagePullSecrets:
  - name: lightspeed-operator-controller-manager-dockercfg-xxhsn
kind: ServiceAccount
metadata:
  name: lightspeed-operator-controller-manager
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lightspeed-cluster-operator-leader-election-role
  namespace: openstack
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lightspeed-operator
  creationTimestamp: null
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - pull-secret
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - config.openshift.io
    resources:
      - apiservers
      - clusterversions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - console.openshift.io
    resources:
      - consoleexternalloglinks
      - consolelinks
      - consoleplugins
      - consoleplugins/finalizers
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ols.openshift.io
    resources:
      - olsconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ols.openshift.io
    resources:
      - olsconfigs/finalizers
    verbs:
      - update
  - apiGroups:
      - ols.openshift.io
    resources:
      - olsconfigs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lightspeed-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lightspeed-operator
subjects:
  - kind: ServiceAccount
    name: lightspeed-operator-controller-manager
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lightspeed-cluster-operator-leader-election-rolebinding
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lightspeed-cluster-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: lightspeed-operator-controller-manager
    namespace: openstack
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: lightspeed-operator-controller-manager
#  labels:
#    control-plane: controller-manager
#spec:
#  ports:
#    - name: metrics
#      port: 8443
#      protocol: TCP
#      targetPort: metrics
#  selector:
#    control-plane: controller-manager
