---
apiVersion: v1
kind: Secret
metadata:
  name: rhelai-secret
  namespace: openstack
type: Opaque
stringData:
  apitoken: '{{ .LLMCredentials }}'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhelai-ca-cert
  namespace: openshift-lightspeed
data:
  cert.crt: |
    '{{ .TLSCert }}'
---
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: rhelai-secret
        models:
          - name: /data/granite-3.1-8b-instruct
            context_window_size: 8192
            parameters:
              max_tokens_for_response: 1024
        name: rhelai
        type: rhelai_vllm
        url: '{{ .LLMEndpoint }}'
  ols:
    defaultProvider: rhelai
    defaultModel: /data/granite-3.1-8b-instruct
    additionalCAConfigMapRef:
      name: rhelai-ca-cert